Update badge price bumps, bucket sizes, and dealer table pricing
magfest/production-config pull request #249
Opened 2017-07-25 23:20 UTC by RobRuana

2017-07-25 23:24 UTC, RobRuana commented on event-prime.yaml
> +uber::config::badge_price_waived: '2018-01-07 12'
Waive badge price at noon of the last day.

2017-07-25 23:24 UTC, RobRuana commented on event-prime.yaml
> +    range_end: 2999
I see no reason why we should give ourselves a large buffer in the badge ranges. Any objections?

2017-07-25 23:24 UTC, RobRuana commented on event-prime.yaml
> +uber::config::one_days_enabled: True
We are enabling one day badges, correct?

2017-07-26 00:16 UTC, RobRuana commented
I'm not 100% up on how the badge pricing dates work in our configuration, so I really need a second set of eyes to review these changes.

From Nick:
> PRICE      BUCKET SIZE      END DATE
> $59            3000                       August 31
> $69            3000                       Sept 30
> $79            4500                       Oct 31
> $85            9500                       Eschaton
> 
> DAY AT EVENT            BADGE PRICE
> Thursday Jan 4               $85
> Friday  Jan 5                    $70
> Saturday Jan 6               $55
> Sunday Jan 7                  $20

From Danielle:
> Danielle proposal for this year:
> uber::config::dealer_badge_price: 45 ($10 change) 
> uber::config::table_prices:
> 1: 150 (no change) 
> 2: 250 ($25 change) 
> 3: 400 ($50 change) 
> 4: 550 ($50 change)

2017-07-26 16:01 UTC, RobRuana commented
I think `max_dealers` is fine as-is; it's defined as:
```
# The max number of badges which a dealer may apply for.
max_dealers = integer(default=20)
```

Also, I set the dealer application shut down to 1 am on August 2nd.

2017-07-26 16:01 UTC, RobRuana commented
And the bucket pricing should be fixed.

2017-07-26 16:28 UTC, kitsuta approved these changes
LGTM!

2017-07-26 16:28 UTC, kitsuta commented on event-prime.yaml
> +    range_end: 2999
Nope, that seems fine!

2017-07-26 16:28 UTC, kitsuta commented on event-prime.yaml
> +uber::config::dealer_reg_start: '2017-07-30 12'     # dealer reg not allowed before this date
These dates are all for the earliest launch window -- do we really want to do that? I have no idea how the office feels about how close we are to ready, but if tomorrow is the greenlight window, it doesn't actually seem like we're ready to greenlight.

2017-07-26 16:30 UTC, RobRuana commented on event-prime.yaml
> +uber::config::dealer_reg_start: '2017-07-30 12'     # dealer reg not allowed before this date
Dealer reg is actually set to open BEFORE preregistration launches. The dealer reg launch has been publicly announced, so it's happening even if preregistration isn't ready. We can launch regular preregistration a week later if needed.

2017-07-26 17:12 UTC, binary1230 requested changes
need 2 minor things but overall looking good to me.

2017-07-26 17:12 UTC, binary1230 commented on event-prime.yaml
> +    range_end: 9999
i think this is an error and these are overlapping

the supporter_badge range is being changed to overlap with the guest_badge range.  both of them say 3000->9999.

double note: it's a legacy quirk that supporter_badge is still it's own badge type (we used to do this, but now when people actually buy a supporter badge, what they really have is an attendee_badge PLUS kickins.)

I'd suggest the following:

```
supporter_badge:     # this badge type is actually obsolete, but removing it may be problematic, so only allocate 100 of them
  range_start:  3000
  range_end:   3100
guest_badge:
  range_start:   3101
  range_end:    9999

2017-07-26 17:12 UTC, binary1230 commented on event-prime.yaml
> +    10500: 85
this was what nick sent:

```
PRICE      BUCKET SIZE      END DATE
$59            3000                       August 31
$69            3000                       Sept 30
$79            4500                       Oct 31
$85            9500                       Eschaton

DAY AT EVENT            BADGE PRICE
Thursday Jan 4               $85
Friday  Jan 5                    $70
Saturday Jan 6               $55
Sunday Jan 7                  $20
```

i think it should read:
```
3000:   69
4500:   79
9500:   85
```

right?

2017-07-26 17:19 UTC, RobRuana commented on event-prime.yaml
> +uber::config::dealer_reg_shutdown: '2017-08-02 1'   # after this date, no new applications allowed
Okay, I understand the short window before we start waitlisting applications. But if we auto-waitlist applications, should it matter? Is a long waitlist cumbersome?

2017-07-26 17:22 UTC, RobRuana commented on event-prime.yaml
> +    10500: 85
I think those bucket sizes are cumulative in the config. The relevant code is:
```python
badges_sold = self.BADGES_SOLD

for badge_cap, bumped_price in sorted(self.PRICE_LIMITS.items()):
    if badges_sold >= badge_cap and bumped_price > price:
        price = bumped_price
```

Where `PRICE_LIMITS` is defined like so:
```python
c.PRICE_BUMPS = {}
c.PRICE_LIMITS = {}
for _opt, _val in c.BADGE_PRICES['attendee'].items():
    try:
        if ' ' in _opt:
            date = c.EVENT_TIMEZONE.localize(datetime.strptime(_opt, '%Y-%m-%d %H%M'))
        else:
            date = c.EVENT_TIMEZONE.localize(datetime.strptime(_opt, '%Y-%m-%d'))
    except ValueError:
        c.PRICE_LIMITS[int(_opt)] = _val
    else:
        c.PRICE_BUMPS[date] = _val
c.ORDERED_PRICE_LIMITS = sorted([val for key, val in c.PRICE_LIMITS.items()])
```

2017-07-26 17:22 UTC, nickthenewbie1 commented on event-prime.yaml
> +    10500: 85
No, the number is the total number if badges sold, not the availability for that tier

2017-07-26 17:23 UTC, RobRuana commented on event-prime.yaml
> +    range_end: 9999
If you look at last years config, both `supporter_badge` and `guest_badge` had the same overlapping ranges. I think the system supports overlapping badge ranges.

2017-07-26 17:24 UTC, RobRuana commented on event-prime.yaml
> +    10500: 85
@nickthenewbie1 were you replying to me or dom?

2017-07-26 17:28 UTC, kitsuta commented on event-prime.yaml
> +    range_end: 9999
The system does support overlapping ranges.

Also, we only kept the badge in because we stopped using it mid-year, so... pretty sure we can remove it now.

2017-07-26 17:43 UTC, nickthenewbie1 commented on event-prime.yaml
> +    10500: 85
Was replying to Dom. The numbers Rob has look ok with me. Double check with Vicki, though.

2017-07-26 18:34 UTC, merged